version: '2'
services:
  db:
    image: rethinkdb
  server:
    build: server
    image: mathiask/weatherdb-server
    ports:
      - "80:3000"
    links:
      - "db:rethinkdb"
    depends_on:
      - "db"
