db:
  image: rethinkdb

server:
  build: server
  ports:
    - "3000:3000"
  links:
    - "db:rethinkdb"

visualization:
  build: visualization
  ports:
    - "8080:80"
  links:
    - "db:rethinkdb"

arduino-mock:
  build: arduino-mock
  links:
    - "server"
