version: '2'
services:
  db:
    image: rethinkdb

  server:
    build: server
    image: mathiask/weatherdb-server
    ports:
      - "3000:3000"
    links:
      - "db:rethinkdb"
    depends_on:
      - "db"

  visualization:
    build: visualization
    image: mathiask/weatherdb-visualization
    ports:
      - "80:80"
    links:
      - "db:rethinkdb"
    depends_on:
      - "db"

  arduino-mock:
    build: arduino-mock
    image: mathiask/weatherdb-arduino-mock
    depends_on:
      - "server"
